### PR TITLE
Add lsp-server configuration

### PR DESCRIPTION
**Pull request by Qquanwei**

### CODE REVIEW

**Comment by Qquanwei** [comment]
According to vue-language-server for vscode

https://github.com/vuejs/vetur/blob/master/server/package.json

**Comment by cryptomaniac512** [comment]
@Qquanwei thank you!
Can you also add usage examples to readme?

**Comment by Qquanwei** [comment]
@cryptomaniac512 Hi . I just put simple config line in here. Because maybe link to `vue-language-server` homepage will be helpful.

**Comment by cryptomaniac512** [comment]
Looks cool! Thank you!

**Pull request merged**
